In [1]:
# Array Oriented Programming

import numpy as np

numbers = np.array([2, 3, 5, 7, 11])

In [2]:
type(numbers)

numpy.ndarray

In [3]:
numbers

array([ 2,  3,  5,  7, 11])

In [4]:
np.array([[1, 2, 3], [10, 20, 30]])

array([[ 1,  2,  3],
       [10, 20, 30]])

In [6]:
# Self Check

even = np.array([number for number in range(1, 21) if number % 2 == 0])

even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
# Self Check 

numbers = np.array([[number for number in range(1,11) if number % 2 == 0], [number for number in range(1,10) if number % 2 != 0]])

numbers

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [11]:
import numpy as np

floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [13]:
numbers.dtype

dtype('int64')

In [14]:
floats.dtype

dtype('float64')

In [15]:
# Dimensions in numpy

numbers.ndim       # This returns the number of columns 

2

In [16]:
#Shapes in np

numbers.shape. # This returns the number of rows and columns

(2, 5)

In [17]:
floats.shape    #This returns only the row

(5,)

In [18]:
# Size of the array

numbers.size

10

In [19]:
floats.size

5

In [21]:
for row in numbers:
    for column in row:
        print(column, end=" ")
    print()

2 4 6 8 10 
1 3 5 7 9 


In [24]:
# Flattening the array

k = []

for i in numbers.flat:
    k.append(i)

k

[2, 4, 6, 8, 10, 1, 3, 5, 7, 9]

In [23]:
numbers

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [25]:
# Numpy functions

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
# Numpy functions

np.ones((2,4), dtype= int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
# Numpy functions

np.full((2,3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [28]:
# Turning ranges of values into array objects

np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
# Turning ranges of values into array objects

np.arange(5, 20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [30]:
# Turning ranges of values into array objects

np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [31]:
# Turning ranges of values into array objects

np.linspace(0.0, 1, num= 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
# Reshape a range

np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
# Reshape a range

np.arange(1, 100001).reshape(4,25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [35]:
# Reshape a range

np.arange(1, 100001).reshape(100,1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [36]:
# Self Check

np.arange(2, 41, 2).reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [37]:
# Array Operations

numbers = np.arange(1, 5)

numbers * 2 # Broadcasting

array([2, 4, 6, 8])

In [39]:
# Array Operations

numbers += 10

numbers

array([21, 22, 23, 24])

In [42]:
# Array Operations

numbers_2 = np.linspace(1.1, 5.5, 4)

numbers_2

array([1.1       , 2.56666667, 4.03333333, 5.5       ])

In [43]:
# Array Operations

numbers + numbers_2

array([22.1       , 24.56666667, 27.03333333, 29.5       ])

In [44]:
# Array Operations

numbers * numbers_2

array([ 23.1       ,  56.46666667,  92.76666667, 132.        ])

In [46]:
# Array Operations

numbers_2 <= 3

array([ True,  True, False, False])

In [48]:
# Array Operations

np.arange(1, 6, 1) ** 2

array([ 1,  4,  9, 16, 25])

In [51]:
# Numpy calculation methods

grades = np.array([[87, 96, 70], [100, 87, 90],
[94, 77, 90], [100, 81, 82]])

grades


array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [52]:
# Numpy calculation methods


grades.sum()

1054

In [53]:
# Numpy calculation methods

grades.min()

70

In [55]:
# Numpy calculation methods

round(grades.mean(),2)

87.83

In [57]:
# Numpy calculation methods

round(grades.std(),3)

8.792

In [58]:
# Numpy calculation methods

round(grades.var(), 3)

77.306

In [60]:
# Numpy calculation methods axes specific

grades.mean(axis=0) # axes = 0 means column


array([95.25, 85.25, 83.  ])

In [62]:
# Numpy calculation methods axes specific

grades.mean(axis=1) # axes = 1 means row

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [63]:
grades.mean?

Docstring:
a.mean(axis=None, dtype=None, out=None, keepdims=False)

Returns the average of the array elements along given axis.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.mean : equivalent function
Type:      builtin_function_or_method


In [64]:
# Self Check

np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 

In [68]:
# Self Check

grades = np.random.randint(60, 100, 12).reshape(3,4)

# Running column means

grades.mean(axis= 0)

array([75.66666667, 76.66666667, 86.33333333, 76.66666667])

In [69]:
# Running row means

grades.mean(axis= 1)

array([72. , 81.5, 83. ])

In [71]:
# Numpy Universal Functions

np.sqrt(numbers)

array([4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [74]:
# Numpy Universal Functions

numbers_2 = np.arange(1, 10) * 100

numbers_3 = np.arange(11, 20)

In [75]:
# Numpy Universal Functions

np.add(numbers_2, numbers_3)

array([111, 212, 313, 414, 515, 616, 717, 818, 919])

In [78]:
# Numpy Universal Functions


np.multiply(numbers_2, numbers_3)

array([ 1100,  2400,  3900,  5600,  7500,  9600, 11900, 14400, 17100])

In [80]:
# Numpy Universal Functions


np.multiply(numbers_3, 5)

array([55, 60, 65, 70, 75, 80, 85, 90, 95])

In [82]:
numbers_4 = numbers.reshape(2, 2)

In [83]:
numbers_5 = np.array([20, 100])

numbers_5

array([ 20, 100])

In [84]:
np.multiply(numbers_4, numbers_5)

array([[ 420, 2200],
       [ 460, 2400]])

In [85]:
numbers_4

array([[21, 22],
       [23, 24]])

In [89]:
# Self Check

array_1 = np.random.randint(90, 200, 5)

np.power(array_1, 3)

array([2248091, 4096000, 5545233, 1860867, 5735339])

In [91]:
# Indexing and slicing Numpy arrays

grades = np.random.randint(60, 100, 12).reshape(3,4)

grades[0,1] # Assessing row 0 and column 1


64

In [92]:
# Indexing and slicing Numpy arrays

# Assessing the last row

grades[2]

array([79, 99, 88, 79])

In [95]:
# Indexing and slicing Numpy arrays

# Assessing the rows 0 and 1 only

grades[0:2]

array([[63, 64, 82, 80],
       [62, 69, 65, 77]])

In [96]:
# Indexing and slicing Numpy arrays

# Assessing the rows 0 and 2 only

grades[[0,2]]

array([[63, 64, 82, 80],
       [79, 99, 88, 79]])

In [98]:
# Indexing and slicing Numpy arrays

# Assessing all the rows in column 2

grades[ : , 2]

array([82, 65, 88])

In [102]:
# Indexing and slicing Numpy arrays

# Assessing all the rows 0 and 2 in columns 1 and 2

grades[ : , 1:3]

array([[64, 82],
       [69, 65],
       [99, 88]])

In [110]:
# Indexing and slicing Numpy arrays

# Assessing all the rows in columns 0 and 2

grades[ : , [0,2]]

array([[63, 82],
       [62, 65],
       [79, 88]])

In [112]:
# Indexing and slicing Numpy arrays

# Assessing the rows 0 and 2 in columns 1 and 2

grades[[0,2] , 1:3]

array([[64, 82],
       [99, 88]])

In [113]:
# Indexing and slicing Numpy arrays

# Assessing the rows 0 and 2 in columns 0 and 2

grades[[0,2] , [0,2]]

array([63, 88])

In [106]:
# Indexing and slicing Numpy arrays

# Assessing  the rows 0 and 1 in columns 1 and 2

grades[ 0:2 , 1:3]

array([[64, 82],
       [69, 65]])

In [ ]:
# Indexing and slicing Numpy arrays

# Assessing  the rows 0 and 1 in columns 1 and 2

grades[ 0:2 , 1:3]

In [104]:
grades

array([[63, 64, 82, 80],
       [62, 69, 65, 77],
       [79, 99, 88, 79]])

In [114]:
# Shallow Copies
array_1 = np.arange(1,11)

array_2 = array_1.view()

In [115]:
# Shallow Copies

array_1[4] **= 3


In [116]:
array_2

# Because array_2 is a view into array_1

array([  1,   2,   3,   4, 125,   6,   7,   8,   9,  10])

In [117]:
array_3 = array_1[0:5]

In [118]:
array_3

array([  1,   2,   3,   4, 125])

In [126]:
array_3[1] **= 6

array_1

array([  1,  64,   1,   4, 125,   6,   7,   8,   9,  10])

In [127]:
# Deep Copies

array_5 = array_1.copy()

array_5[0] = 10000

array_5

array([10000,    64,     1,     4,   125,     6,     7,     8,     9,
          10])

In [129]:
# Reshaping and transposing arrays

grades = np.array([[87, 96, 70], [100, 87, 90]])

grades.reshape(1,6) # This is just a view

array([[ 87,  96,  70, 100,  87,  90]])

In [131]:
# Resizing grades

grades.resize(3,2)

grades

array([[ 87,  96],
       [ 70, 100],
       [ 87,  90]])

In [133]:
# Flatten and ravel

flattened = grades.flatten()

flattened # This creates a deep copy

array([ 87,  96,  70, 100,  87,  90])

In [134]:
flattened[-1] = 100000

flattened

array([    87,     96,     70,    100,     87, 100000])

In [135]:
grades

array([[ 87,  96],
       [ 70, 100],
       [ 87,  90]])

In [137]:
raveled = grades.ravel()


raveled
# This creates a shallow copy

array([ 87,  96,  70, 100,  87,  90])

In [138]:
# Still multidimensional

grades 

array([[ 87,  96],
       [ 70, 100],
       [ 87,  90]])

In [139]:
# modifying ravel affects grades (hence shallow copy)


raveled[2] = 100000

grades

array([[    87,     96],
       [100000,    100],
       [    87,     90]])

In [140]:
# Transposing rows and columns

grades.T

array([[    87, 100000,     87],
       [    96,    100,     90]])

In [141]:
# Horizontal and Vertical stacking

grades_2 = np.array([[98, 34], [88,78], [90,79]])

grades_2

array([[98, 34],
       [88, 78],
       [90, 79]])

In [142]:
# Using the hstack method

np.hstack((grades, grades_2))

array([[    87,     96,     98,     34],
       [100000,    100,     88,     78],
       [    87,     90,     90,     79]])

In [143]:
# Using the vstack method

np.vstack((grades, grades_2))

array([[    87,     96],
       [100000,    100],
       [    87,     90],
       [    98,     34],
       [    88,     78],
       [    90,     79]])

In [144]:
# Pandas: Series and Dataframes

import pandas as pd

grades = pd.Series([87, 100, 94])

grades

0     87
1    100
2     94
dtype: int64

In [146]:
# Produce a repeat series with the same number

pd.Series(90.2, range(11))

0     90.2
1     90.2
2     90.2
3     90.2
4     90.2
5     90.2
6     90.2
7     90.2
8     90.2
9     90.2
10    90.2
dtype: float64

In [147]:
grades[0]

87

In [148]:
grades.mean()

93.66666666666667

In [149]:
# Producing summary descriptive statistics

grades.describe()


count      3.000000
mean      93.666667
std        6.506407
min       87.000000
25%       90.500000
50%       94.000000
75%       97.000000
max      100.000000
dtype: float64

In [150]:
# Custom indices

grades = pd.Series([87, 98, 79], index=["Wally", "Maame", "Ewura"])

grades

Wally    87
Maame    98
Ewura    79
dtype: int64

In [151]:
# Same output as above with dictionaries

grades_2 = pd.Series({"Wally": 87, "Maame": 98, "Ewura": 79})

grades_2

Wally    87
Maame    98
Ewura    79
dtype: int64

In [152]:
# Indexing to produce a numpy array

grades.values

array([87, 98, 79])

In [153]:
grades_2["Maame"]

98

In [154]:
# Strings containng integers

names = pd.Series(["Hammer", "Saw", "Wrench"])

names

0    Hammer
1       Saw
2    Wrench
dtype: object

In [155]:
# Which elements of the series have an "s"

names.str.contains("s")
# Notice "s" != "S"

0    False
1    False
2    False
dtype: bool

In [158]:
# Which elements of the series have an "S"

names.str.contains("S")

False

In [164]:
names.str.upper()

0    HAMMER
1       SAW
2    WRENCH
dtype: object

In [169]:
# Self Check

from random import randrange

temp = np.array([randrange(60, 100) for t in range(5)])


# Converting from Numpy to pandas

temperature = pd.Series(temp)

# Producing Descriptive stats for the series

temperature.describe()

count     5.000000
mean     71.400000
std       8.080842
min      62.000000
25%      69.000000
50%      69.000000
75%      73.000000
max      84.000000
dtype: float64

In [171]:
# Self Check

from random import randint


# A series of five integers b/n 60-100
temp = np.random.randint(60, 100, 5)


# Converting from Numpy to pandas

temperature = pd.Series(temp)

# Producing Descriptive stats for the series

temperature.describe()

count     5.000000
mean     83.800000
std      12.029131
min      63.000000
25%      85.000000
50%      87.000000
75%      92.000000
max      92.000000
dtype: float64

In [184]:
# Pandas: Dataframes

import pandas as pd

import random


# Create a grades dataframes

grades_dict = {"Wally" : [random.randint(70, 100) for i in range(5)], "Maame" : [random.randint(70, 100) for i in range(5)], "Clive" : [random.randint(70, 100) for i in range(5)], "John" : [random.randint(70, 100) for i in range(5)], "Yaw" : [random.randint(70, 100) for i in range(5)] }

# Converting the grades dictionary to pandas Dataframe

grades = pd.DataFrame(grades_dict)


grades

Wally  Maame  Clive  John  Yaw
0     83     86     70    94   87
1     89     73     77    82   80
2     81     71     80    86   88
3     73     96     70    79   97
4     90     99     90    95   75

In [235]:
# New index for grades

grades.index = ["a", "b", "c", "d", "e"]

grades

Wally  Maame  Clive  John    Yaw
a     83     86     70    94     87
b     89     73     77    82     80
c     81     71     80    86     88
d     73     96     70    79     97
e     90     99     90    95  10000

In [186]:
# Indexing Dataframes

grades["Yaw"]

a    87
b    80
c    88
d    97
e    75
Name: Yaw, dtype: int64

In [187]:
# Indexing Dataframes

grades.Maame

a    86
b    73
c    71
d    96
e    99
Name: Maame, dtype: int64

In [191]:
# Assessing the rows

grades.loc["a"]

Wally    83
Maame    86
Clive    70
John     94
Yaw      87
Name: a, dtype: int64

In [193]:
# Assessing the rows 

grades.iloc[3]

Wally    73
Maame    96
Clive    70
John     79
Yaw      97
Name: d, dtype: int64

In [194]:
# Assessing the rows 0, 1 and 2

grades.iloc[0:3]

Wally  Maame  Clive  John  Yaw
a     83     86     70    94   87
b     89     73     77    82   80
c     81     71     80    86   88

In [196]:
# Assessing the rows 0, 2 and 4

grades.iloc[[0,2,4]]

Wally  Maame  Clive  John  Yaw
a     83     86     70    94   87
c     81     71     80    86   88
e     90     99     90    95   75

In [198]:
# Assessing the rows 0, 2 and 4

grades.loc[["a", "c", "e"]]

Wally  Maame  Clive  John  Yaw
a     83     86     70    94   87
c     81     71     80    86   88
e     90     99     90    95   75

In [199]:
# Assessing the rows and columns

grades.iloc[[0,2,4], [1,4]]

Maame  Yaw
a     86   87
c     71   88
e     99   75

In [200]:
# Assessing the rows and columns

grades.loc[["a", "c"], ["Yaw", "Clive"]]

Yaw  Clive
a   87     70
c   88     80

In [201]:
# Boolean indexing

grades[grades >= 90 ]

Wally  Maame  Clive  John   Yaw
a    NaN    NaN    NaN  94.0   NaN
b    NaN    NaN    NaN   NaN   NaN
c    NaN    NaN    NaN   NaN   NaN
d    NaN   96.0    NaN   NaN  97.0
e   90.0   99.0   90.0  95.0   NaN

In [202]:
# Boolean indexing

grades[(grades >= 80) & (grades <= 90)]

Wally  Maame  Clive  John   Yaw
a   83.0   86.0    NaN   NaN  87.0
b   89.0    NaN    NaN  82.0  80.0
c   81.0    NaN   80.0  86.0  88.0
d    NaN    NaN    NaN   NaN   NaN
e   90.0    NaN   90.0   NaN   NaN

In [203]:
# Using the at atribute

grades.at["b", "Clive"]

77

In [204]:
# Using the at atribute

grades.iat[4, 0]

90

In [205]:
# Assignment with at

grades.at["e", "Yaw"] = 10000

grades

Wally  Maame  Clive  John    Yaw
a     83     86     70    94     87
b     89     73     77    82     80
c     81     71     80    86     88
d     73     96     70    79     97
e     90     99     90    95  10000

In [208]:
# Descriptive statistics on dataframes with numeric columns

grades.describe()

Wally      Maame      Clive       John           Yaw
count   5.000000   5.000000   5.000000   5.000000      5.000000
mean   83.200000  85.000000  77.400000  87.200000   2070.400000
std     6.870226  12.825755   8.294577   7.120393   4432.785276
min    73.000000  71.000000  70.000000  79.000000     80.000000
25%    81.000000  73.000000  70.000000  82.000000     87.000000
50%    83.000000  86.000000  77.000000  86.000000     88.000000
75%    89.000000  96.000000  80.000000  94.000000     97.000000
max    90.000000  99.000000  90.000000  95.000000  10000.000000

In [209]:
# seting the options for pandas

pd.set_option("precision", 3)

In [210]:
# Descriptive statistics on dataframes with numeric columns

grades.describe()

Wally   Maame   Clive   John        Yaw
count   5.00   5.000   5.000   5.00      5.000
mean   83.20  85.000  77.400  87.20   2070.400
std     6.87  12.826   8.295   7.12   4432.785
min    73.00  71.000  70.000  79.00     80.000
25%    81.00  73.000  70.000  82.00     87.000
50%    83.00  86.000  77.000  86.00     88.000
75%    89.00  96.000  80.000  94.00     97.000
max    90.00  99.000  90.000  95.00  10000.000

In [211]:
# Column means

grades.mean()

Wally      83.2
Maame      85.0
Clive      77.4
John       87.2
Yaw      2070.4
dtype: float64

In [212]:
# Row means

grades.T.mean()

a      84.0
b      80.2
c      81.2
d      83.0
e    2074.8
dtype: float64

In [213]:
# Row summary

grades.T.describe()

a       b       c       d          e
count   5.000   5.000   5.000   5.000      5.000
mean   84.000  80.200  81.200  83.000   2074.800
std     8.803   5.975   6.611  12.748   4430.323
min    70.000  73.000  71.000  70.000     90.000
25%    83.000  77.000  80.000  73.000     90.000
50%    86.000  80.000  81.000  79.000     95.000
75%    87.000  82.000  86.000  96.000     99.000
max    94.000  89.000  88.000  97.000  10000.000

In [214]:
# Sorting by index

grades.sort_index(ascending=False)

Wally  Maame  Clive  John    Yaw
e     90     99     90    95  10000
d     73     96     70    79     97
c     81     71     80    86     88
b     89     73     77    82     80
a     83     86     70    94     87

In [216]:
# Sorting by column names

grades.sort_index(axis=1)

# ordering by column heads

Clive  John  Maame  Wally    Yaw
a     70    94     86     83     87
b     77    82     73     89     80
c     80    86     71     81     88
d     70    79     96     73     97
e     90    95     99     90  10000

In [225]:
# Sorting by values within the dataframe

grades.sort_values(by="e", axis= 1, ascending=False)

Yaw  Maame  John  Wally  Clive
a     87     86    94     83     70
b     80     73    82     89     77
c     88     71    86     81     80
d     97     96    79     73     70
e  10000     99    95     90     90

In [226]:
grades.T.sort_values(by= "e", ascending=False)

a   b   c   d      e
Yaw    87  80  88  97  10000
Maame  86  73  71  96     99
John   94  82  86  79     95
Wally  83  89  81  73     90
Clive  70  77  80  70     90

In [227]:
# Returning a single column output

grades.loc["e"].sort_values(ascending=False)

Yaw      10000
Maame       99
John        95
Wally       90
Clive       90
Name: e, dtype: int64

In [233]:
# Self Check
temps = {"Mon" : [68, 89], "Tue" : [71, 93], "Wed" : [66, 82], "Thu" : [75, 97], "Fri" : [62, 79]}

# Converting temps to a Dataframe

temperatures = pd.DataFrame(temps)

# Changing the indices

temperatures.index = ["low", "high"]


Mon  Tue  Wed  Thu  Fri
0   68   71   66   75   62
1   89   93   82   97   79

In [255]:
# Selecting only Mon and Tue

temperatures.iloc[[0,1], [0,1,2]]

Mon  Tue  Wed
low    68   71   66
high   89   93   82

In [256]:
# Row index

temperatures.loc["low"]

Mon    68
Tue    71
Wed    66
Thu    75
Fri    62
Name: low, dtype: int64

In [257]:
pd.set_option("precision", 3)

In [260]:
# Average Daily Temperature

temperatures.mean()

Mon    78.5
Tue    82.0
Wed    74.0
Thu    86.0
Fri    70.5
dtype: float64